services:
  couscous_api:
    build: ./CouscousApi/.
    container_name: couscous_api
    volumes:
      - ./:/App:delegated
    ports:
      - "12345:8080"
    working_dir: /app/
    depends_on:
      couscous_postgres:
        condition: service_healthy
  couscous_postgres:
    image: postgres
    container_name: couscous_postgres
    ports:
      - "5432:5432"
    volumes:
      - couscous-postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=couscous
      - POSTGRES_PASSWORD=couscous
      - POSTGRES_USER=couscous
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 5s
      timeout: 2s
      retries: 5

volumes:
  couscous-postgres-data:
