services:
  couscous_api:
    build: ./CouscousApi/.
    container_name: couscous_api
    volumes:
      - ./:/App:delegated
    ports:
      - "12345:8080"
    working_dir: /app/
    depends_on:
      couscous_postgres:
        condition: service_healthy
      couscous_elasticsearch:
        condition: service_healthy

  couscous_kibana:
    image: kibana:8.13.3
    container_name: couscous_kibana
    environment:
      ELASTICSEARCH_HOSTS: '["http://couscous_elasticsearch:9200","http://couscous_elasticsearch:9300"]'
    ports:
      - 5601:5601
    depends_on:
      couscous_elasticsearch:
        condition: service_healthy

  couscous_elasticsearch:
    image: elasticsearch:8.13.3
    container_name: couscous_elasticsearch
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      xpack.security.enabled: false
      xpack.security.http.ssl.enabled: false
    ports:
      - 9200:9200
      - 9300:9300
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
      interval: 10s
      timeout: 30s
      retries: 3

  couscous_postgres:
    image: postgres
    container_name: couscous_postgres
    ports:
      - "5432:5432"
    volumes:
      - couscous-postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=couscous
      - POSTGRES_PASSWORD=couscous
      - POSTGRES_USER=couscous
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 5s
      timeout: 2s
      retries: 5

volumes:
  couscous-postgres-data:
